const skills = [
    "JavaScript",
    "HTML5",
    "CSS3",
    "ReactJS",
    "SQL",
    "MYSQL",
    "GRAPHQL",
    "Git",
    "Wix",
    "WordPress",
    "Testing",
    "JQuery",
    "TypeScript",
    "Express",
    "MongoDB",
    "Handlebars.js",
    "Bootstrap",
    "NoSQL",
    "Node.js",
    "Communication",
    "Collaboration",
    "Adobe Express",
    "Adobe Illustrator",
    "Google Sheets",
    "MailChimp",
    "Stripe",
    "Square",
    "Data Management",
]

export default skills;